# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
#
development:
  adapter: postgresql
  encoding: utf8
  database: jsonapi_robot_wars
  pool: 5
  username: angular_jsonapi
  password: a